apiVersion: v2
name: helm-grafana-soc
version: 1.0.0
appVersion: 1.23.0
description: A Helm chart wrapper for Grafana

dependencies:
  - name: grafana
    version: "6.30.0"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled
